// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ntt_HH_
#define _ntt_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "ntt_zetas.h"

namespace ap_rtl {

struct ntt : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<8> > p_address0;
    sc_out< sc_logic > p_ce0;
    sc_out< sc_logic > p_we0;
    sc_out< sc_lv<32> > p_d0;
    sc_in< sc_lv<32> > p_q0;


    // Module declarations
    ntt(sc_module_name name);
    SC_HAS_PROCESS(ntt);

    ~ntt();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    ntt_zetas* zetas_U;
    sc_signal< sc_lv<12> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > zetas_address0;
    sc_signal< sc_logic > zetas_ce0;
    sc_signal< sc_lv<23> > zetas_q0;
    sc_signal< sc_lv<31> > len_cast_cast4_fu_146_p1;
    sc_signal< sc_lv<31> > len_cast_cast4_reg_427;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_fu_166_p2;
    sc_signal< sc_lv<29> > len_1_fu_190_p1;
    sc_signal< sc_lv<32> > k_1_fu_194_p2;
    sc_signal< sc_lv<32> > k_1_reg_455;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<31> > tmp_4_fu_199_p2;
    sc_signal< sc_lv<31> > tmp_4_reg_460;
    sc_signal< sc_lv<31> > start_cast_fu_226_p1;
    sc_signal< sc_lv<31> > start_cast_reg_465;
    sc_signal< sc_lv<55> > tmp_6_cast_fu_230_p1;
    sc_signal< sc_lv<55> > tmp_6_cast_reg_470;
    sc_signal< sc_lv<8> > p_addr_reg_478;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > tmp_8_fu_234_p2;
    sc_signal< sc_lv<8> > p_addr_1_reg_483;
    sc_signal< sc_lv<31> > j_1_fu_254_p2;
    sc_signal< sc_lv<31> > j_1_reg_488;
    sc_signal< sc_lv<31> > tmp_13_fu_260_p2;
    sc_signal< sc_lv<32> > p_load_reg_498;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<55> > a_assign_fu_271_p2;
    sc_signal< sc_lv<55> > a_assign_reg_503;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > temp_fu_276_p1;
    sc_signal< sc_lv<32> > temp_reg_508;
    sc_signal< sc_lv<6> > tmp_19_fu_280_p1;
    sc_signal< sc_lv<6> > tmp_19_reg_513;
    sc_signal< sc_lv<9> > tmp_20_fu_284_p1;
    sc_signal< sc_lv<9> > tmp_20_reg_518;
    sc_signal< sc_lv<19> > tmp_21_fu_288_p1;
    sc_signal< sc_lv<19> > tmp_21_reg_523;
    sc_signal< sc_lv<32> > temp_1_fu_324_p2;
    sc_signal< sc_lv<32> > temp_1_reg_528;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<25> > tmp_7_reg_535;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<29> > len_reg_107;
    sc_signal< sc_lv<31> > j_reg_119;
    sc_signal< sc_lv<1> > tmp_fu_150_p2;
    sc_signal< sc_lv<31> > j1_reg_131;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<64> > tmp_3_fu_175_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_244_p1;
    sc_signal< sc_lv<64> > tmp_6_fu_249_p1;
    sc_signal< sc_lv<32> > k_fu_70;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<32> > tmp_11_fu_403_p2;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<32> > tmp_12_fu_413_p2;
    sc_signal< sc_lv<23> > tmp_1_fu_156_p4;
    sc_signal< sc_lv<28> > tmp_17_fu_180_p4;
    sc_signal< sc_lv<1> > tmp_5_fu_204_p2;
    sc_signal< sc_lv<30> > tmp_14_fu_210_p1;
    sc_signal< sc_lv<30> > tmp_15_fu_214_p1;
    sc_signal< sc_lv<30> > start_fu_218_p3;
    sc_signal< sc_lv<31> > tmp_9_fu_239_p2;
    sc_signal< sc_lv<23> > a_assign_fu_271_p0;
    sc_signal< sc_lv<32> > a_assign_fu_271_p1;
    sc_signal< sc_lv<32> > tmp_i_9_fu_299_p3;
    sc_signal< sc_lv<32> > sum_neg_i_fu_313_p2;
    sc_signal< sc_lv<32> > tmp_i_fu_292_p3;
    sc_signal< sc_lv<32> > sum3_neg_i_fu_318_p2;
    sc_signal< sc_lv<32> > tmp_15_i_fu_306_p3;
    sc_signal< sc_lv<55> > tmp_16_i_fu_333_p3;
    sc_signal< sc_lv<45> > tmp_17_i_fu_344_p3;
    sc_signal< sc_lv<55> > t_cast_fu_330_p1;
    sc_signal< sc_lv<55> > tmp1_fu_355_p2;
    sc_signal< sc_lv<56> > tmp_16_i_cast_fu_340_p1;
    sc_signal< sc_lv<56> > tmp1_cast_fu_360_p1;
    sc_signal< sc_lv<56> > tmp_19_i_fu_364_p2;
    sc_signal< sc_lv<57> > tmp_19_i_cast_fu_370_p1;
    sc_signal< sc_lv<57> > tmp_17_i_cast_fu_351_p1;
    sc_signal< sc_lv<57> > t_fu_374_p2;
    sc_signal< sc_lv<26> > t_1_cast_fu_390_p1;
    sc_signal< sc_lv<26> > tmp_10_fu_393_p2;
    sc_signal< sc_lv<32> > tmp_10_cast_fu_399_p1;
    sc_signal< sc_lv<32> > t_1_fu_410_p1;
    sc_signal< sc_lv<12> > ap_NS_fsm;
    sc_signal< sc_lv<55> > a_assign_fu_271_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<12> ap_ST_fsm_state1;
    static const sc_lv<12> ap_ST_fsm_state2;
    static const sc_lv<12> ap_ST_fsm_state3;
    static const sc_lv<12> ap_ST_fsm_state4;
    static const sc_lv<12> ap_ST_fsm_state5;
    static const sc_lv<12> ap_ST_fsm_state6;
    static const sc_lv<12> ap_ST_fsm_state7;
    static const sc_lv<12> ap_ST_fsm_state8;
    static const sc_lv<12> ap_ST_fsm_state9;
    static const sc_lv<12> ap_ST_fsm_state10;
    static const sc_lv<12> ap_ST_fsm_state11;
    static const sc_lv<12> ap_ST_fsm_state12;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<29> ap_const_lv29_80;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<29> ap_const_lv29_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<31> ap_const_lv31_1;
    static const sc_lv<26> ap_const_lv26_0;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_38;
    static const sc_lv<26> ap_const_lv26_FFC002;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_a_assign_fu_271_p0();
    void thread_a_assign_fu_271_p1();
    void thread_a_assign_fu_271_p10();
    void thread_a_assign_fu_271_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_icmp_fu_166_p2();
    void thread_j_1_fu_254_p2();
    void thread_k_1_fu_194_p2();
    void thread_len_1_fu_190_p1();
    void thread_len_cast_cast4_fu_146_p1();
    void thread_p_address0();
    void thread_p_ce0();
    void thread_p_d0();
    void thread_p_we0();
    void thread_start_cast_fu_226_p1();
    void thread_start_fu_218_p3();
    void thread_sum3_neg_i_fu_318_p2();
    void thread_sum_neg_i_fu_313_p2();
    void thread_t_1_cast_fu_390_p1();
    void thread_t_1_fu_410_p1();
    void thread_t_cast_fu_330_p1();
    void thread_t_fu_374_p2();
    void thread_temp_1_fu_324_p2();
    void thread_temp_fu_276_p1();
    void thread_tmp1_cast_fu_360_p1();
    void thread_tmp1_fu_355_p2();
    void thread_tmp_10_cast_fu_399_p1();
    void thread_tmp_10_fu_393_p2();
    void thread_tmp_11_fu_403_p2();
    void thread_tmp_12_fu_413_p2();
    void thread_tmp_13_fu_260_p2();
    void thread_tmp_14_fu_210_p1();
    void thread_tmp_15_fu_214_p1();
    void thread_tmp_15_i_fu_306_p3();
    void thread_tmp_16_i_cast_fu_340_p1();
    void thread_tmp_16_i_fu_333_p3();
    void thread_tmp_17_fu_180_p4();
    void thread_tmp_17_i_cast_fu_351_p1();
    void thread_tmp_17_i_fu_344_p3();
    void thread_tmp_19_fu_280_p1();
    void thread_tmp_19_i_cast_fu_370_p1();
    void thread_tmp_19_i_fu_364_p2();
    void thread_tmp_1_fu_156_p4();
    void thread_tmp_20_fu_284_p1();
    void thread_tmp_21_fu_288_p1();
    void thread_tmp_3_fu_175_p1();
    void thread_tmp_4_fu_199_p2();
    void thread_tmp_5_fu_204_p2();
    void thread_tmp_6_cast_fu_230_p1();
    void thread_tmp_6_fu_249_p1();
    void thread_tmp_8_fu_234_p2();
    void thread_tmp_9_fu_239_p2();
    void thread_tmp_fu_150_p2();
    void thread_tmp_i_9_fu_299_p3();
    void thread_tmp_i_fu_292_p3();
    void thread_tmp_s_fu_244_p1();
    void thread_zetas_address0();
    void thread_zetas_ce0();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
