// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_ntt (
unsigned int q0[32],
unsigned int q1[32],
unsigned int q2[32],
unsigned int q3[32],
unsigned int q4[32],
unsigned int q5[32],
unsigned int q6[32],
unsigned int q7[32],
unsigned int zetas[256]);
